ignorando archivos diferencia de import de netmail o echomail

diff --git a/ftn2mhs b/ftn2mhs
--- a/ftn2mhs
+++ b/ftn2mhs
@@ -34,24 +34,56 @@ mhs_import() {
         BODY=`echo $MSG_TEXT | sed -e '1,/^$/d'`
         OUT_FILE=`basename $msg .msg`
 
-        echo $HEADERS
-        # From
-        echo $HEADERS | grep "From:" >$PATH_MHS_IN/$OUT_FILE
-        # To
-        to_line=`echo $HEADERS | grep "To: "`
-        IFS=':'
-        read -r field value <<< "$to_line"
-        to_name=`echo $value | cut -f 1 -d "@"`
-        IFS=""
-        echo "To: $to_name @ MBBS {MBBS: $to_name}" >> $PATH_MHS_IN/$OUT_FILE
-        # Subject
-        echo $HEADERS | grep "Subject:" >>$PATH_MHS_IN/$OUT_FILE
-        # Summary
-        echo "Summary: MBBS: $to_name" >>$PATH_MHS_IN/$OUT_FILE
-        # Date
-        echo $HEADERS | grep "Date:" >>$PATH_MHS_IN/$OUT_FILE
-        echo -e "\r\n" >>$PATH_MHS_IN/$OUT_FILE 
-        echo $BODY >>$PATH_MHS_IN/$OUT_FILE
+        #detect netmail/echomail
+        detected=1
+        echo $HEADERS |grep "Flags:" |grep -i PRIVATE
+        if [ $? -eq 0 ]; then
+            is_private=1
+        else
+            echo $HEADERS |grep "Area:"
+            if [ $? -eq 0 ]; then 
+                is_private=0
+                area=`echo $HEADERS |grep "Area:" | cut -f 2 -d ":"`
+                area=`trim $area`
+            else
+                echo "ERROR: can detect msg type (netmail/echomail)"
+                detected=0
+            fi
+        fi
+        if [ $detected -eq 1 ]; then
+            echo $HEADERS
+
+            # From
+            echo $HEADERS | grep "From:" >$PATH_MHS_IN/$OUT_FILE
+
+            if [ $is_private -eq 1 ]; then
+                # To
+                to_line=`echo $HEADERS | grep "To: "`
+                IFS=':'
+                read -r field value <<< "$to_line"
+                to_name=`echo $value | cut -f 1 -d "@"`
+                IFS=""
+                to_name=`trim $to_name`
+                echo "To: $to_name @ MBBS {MBBS: $to_name}" >> $PATH_MHS_IN/$OUT_FILE
+                # Summary
+                value=`trim $value`
+                echo "Summary: MBBS: $value" >>$PATH_MHS_IN/$OUT_FILE
+            else
+                # To
+                echo "To: /$area @ MBBS {MBBS: /$area}" >> $PATH_MHS_IN/$OUT_FILE
+                # Summary
+                echo "Summary: MBBS: $value" >>$PATH_MHS_IN/$OUT_FILE
+            fi
+
+            # Subject
+            echo $HEADERS | grep "Subject:" >>$PATH_MHS_IN/$OUT_FILE
+
+            # Date
+            echo $HEADERS | grep "Date:" >>$PATH_MHS_IN/$OUT_FILE
+            echo -e "\r\n" >>$PATH_MHS_IN/$OUT_FILE 
+            echo $BODY >>$PATH_MHS_IN/$OUT_FILE
+
+        fi
     done
 }
 
